<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Support\Str;

class Currency extends Model
{
    use HasFactory;

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static ::creating(function ($model) {
           $model->slug=Str::slug($model->title);
        });

        static ::updating(function ($model) {
            $model->slug=Str::slug($model->title);
        });
    }

    public function product():HasMany
    {
        return $this->hasMany(Product::class,'product_id');
    }
}
